import { read, utils } from 'xlsx';
import { extractSourceDate, inferOrganisation } from './domain-hardening';

export type BackfillSource = { key: string; territory: string; method: string; endpoint: string; provenance: string };
export type RawRow = { externalId: string; raw: Record<string, unknown> };
export type Page = { rows: RawRow[]; next: number; completed: boolean };
export type Evidence = { sourceKey: string; externalId: string; project: string; company: string; organisationRole?: 'DELIVERY_CONTRACTOR'|'OWNER_PROPONENT'|'APPLICANT_HOLDER'|'SUPPLIER'|'OPERATOR'|'UNKNOWN'; location: string; description: string; observedAt: string; sourceObservedAt?: string; provenance: string; evidenceType: 'EXPLICIT' };
const BATCH = 100;
const MAX_DAYS = 3650;
const text = (v: unknown) => typeof v === 'string' ? v.trim() : v == null ? '' : String(v);
const stripHtml = (v: unknown) => text(v).replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
const find = (row: Record<string, unknown>, parts: string[]) => { for (const [key, value] of Object.entries(row)) { const normalized = key.toLowerCase().replace(/[^a-z0-9]/g, ''); if (parts.some(part => normalized.includes(part.replace(/[^a-z0-9]/g, '')))) { const result = text(value); if (result) return result; } } return ''; };

async function request(url: string, accept: string) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 15000); try { return await fetch(url, { signal: controller.signal, headers: { accept, 'user-agent': 'HirerIntelligence/1.0 historical-open-data-client' } }); } finally { clearTimeout(timer); } }
async function jsonFetch(url: string) { const response = await request(url, 'application/json'); if (!response.ok) throw new Error('HTTP_' + response.status); const body = await response.json(); if (!body || typeof body !== 'object') throw new Error('SCHEMA_INVALID'); return body as Record<string, unknown>; }
async function textFetch(url: string) { const response = await request(url, 'application/xml,text/xml,text/plain'); if (!response.ok) throw new Error('HTTP_' + response.status); return response.text(); }
async function workbook(url: string) { const response = await request(url, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); if (!response.ok) throw new Error('HTTP_' + response.status); return read(await response.arrayBuffer(), { type: 'array' }); }

export function normalizeEvidence(source: BackfillSource, row: RawRow, observedAt: string): Evidence { const organisation=inferOrganisation(source.key,row.raw); return { sourceKey: source.key, externalId: row.externalId, project: find(row.raw, ['projectname','projecttitle','tenement','tenure','permitnumber','authoritynumber','contractid','title','name','description']) || row.externalId, company: organisation.name, organisationRole: organisation.role, location: find(row.raw, ['locality','location','shire','lga','miningdistrict','region','district','area','state']) || source.territory, description: find(row.raw, ['description','activity','purpose','commodity','resource','permittype','type','status','industry']), observedAt, sourceObservedAt: extractSourceDate(row.raw, observedAt), provenance: source.provenance, evidenceType: 'EXPLICIT' }; }
function params(sourceUrl: string, values: Record<string, string>) { const url = new URL(sourceUrl); Object.entries(values).forEach(([key, value]) => url.searchParams.set(key, value)); return url.toString(); }

async function arcgis(source: BackfillSource, cursor: number): Promise<Page> { const body = await jsonFetch(params(source.endpoint, { resultOffset: String(cursor), resultRecordCount: String(BATCH), f: 'json' })) as any; if (!Array.isArray(body.features)) throw new Error('ARCGIS_SCHEMA_INVALID'); const rows = body.features.map((feature: any, index: number) => ({ externalId: text(feature.attributes?.OBJECTID || feature.attributes?.TENID || feature.attributes?.id || cursor + index + 1), raw: (feature.attributes || {}) as Record<string, unknown> })); return { rows, next: cursor + rows.length, completed: rows.length < BATCH }; }
async function datastore(source: BackfillSource, cursor: number): Promise<Page> { const body = await jsonFetch(params(source.endpoint, { limit: String(BATCH), offset: String(cursor) })) as any; if (body.success !== true || !Array.isArray(body.result?.records)) throw new Error('CKAN_SCHEMA_INVALID'); const rows = body.result.records.map((row: any, index: number) => ({ externalId: text(row._id || row.id || cursor + index + 1), raw: row as Record<string, unknown> })); const total = Number(body.result.total || 0); return { rows, next: cursor + rows.length, completed: rows.length < BATCH || (total > 0 && cursor + rows.length >= total) }; }
async function ods(source: BackfillSource, cursor: number): Promise<Page> { const url=new URL(source.endpoint);url.searchParams.delete('order_by');url.searchParams.set('limit',String(BATCH));url.searchParams.set('offset',String(cursor)); let body:any; try{body=await jsonFetch(url.toString()) as any}catch(error){if(error instanceof Error&&error.message==='HTTP_400'&&cursor===0){url.searchParams.delete('offset');body=await jsonFetch(url.toString()) as any}else throw error} if (!Array.isArray(body.results)) throw new Error('ODS_SCHEMA_INVALID'); const rows = body.results.map((row: any, index: number) => ({ externalId: text(row.recordid || row.id || row.permit_number || row.project_id || cursor + index + 1), raw: row as Record<string, unknown> })); const total = Number(body.total_count || 0); return { rows, next: cursor + rows.length, completed: rows.length < BATCH || (total > 0 && cursor + rows.length >= total) }; }
async function wfs(source: BackfillSource, cursor: number): Promise<Page> { const capabilities = await textFetch(source.endpoint + '?service=WFS&version=1.1.0&request=GetCapabilities'); const names = [...capabilities.matchAll(/<(?:\w+:)?FeatureType>([\s\S]*?)<\/(?:\w+:)?FeatureType>/gi)].map(match => match[1].match(/<(?:\w+:)?Name>([^<]+)<\/(?:\w+:)?Name>/i)?.[1]?.trim() || '').filter(Boolean); if (!names.length) throw new Error('WFS_NO_FEATURE_TYPES'); for (const name of names.slice(0, 4)) { try { const body = await jsonFetch(source.endpoint + '?service=WFS&version=1.1.0&request=GetFeature&typeName=' + encodeURIComponent(name) + '&outputFormat=application%2Fjson&maxFeatures=' + BATCH + '&startIndex=' + cursor) as any; if (!Array.isArray(body.features)) continue; const rows = body.features.map((feature: any, index: number) => ({ externalId: text(feature.id || feature.properties?.OBJECTID || feature.properties?.id || cursor + index + 1), raw: (feature.properties || {}) as Record<string, unknown> })); return { rows, next: cursor + rows.length, completed: rows.length < BATCH }; } catch { continue; } } throw new Error('WFS_NO_JSON_FEATURES'); }
async function wfsDirect(source: BackfillSource, cursor: number): Promise<Page> { const body = await jsonFetch(params(source.endpoint, { count: String(BATCH), startIndex: String(cursor) })) as any; if (!Array.isArray(body.features)) throw new Error('WFS_DIRECT_SCHEMA_INVALID'); const rows = body.features.map((feature: any, index: number) => ({ externalId: text(feature.id || feature.properties?.tas_id || feature.properties?.title_id || feature.properties?.title_no || cursor + index + 1), raw: (feature.properties || {}) as Record<string, unknown> })); const matched = Number(body.numberMatched || body.totalFeatures || 0); return { rows, next: cursor + rows.length, completed: rows.length < BATCH || (matched > 0 && cursor + rows.length >= matched) }; }
async function ocds(source: BackfillSource, cursor: number): Promise<Page> { const end = new Date(Date.now() - cursor * 86400000); const start = new Date(end.getTime() - 7 * 86400000); const iso = (date: Date) => date.toISOString().replace(/\.\d{3}Z$/, 'Z'); const body = await jsonFetch(source.endpoint + '/' + iso(start) + '/' + iso(end)) as any; const releases = Array.isArray(body.releases) ? body.releases : Array.isArray(body.records) ? body.records.flatMap((record: any) => record.releases || []) : []; const rows = releases.slice(0, BATCH).map((release: any, index: number) => { const contract = Array.isArray(release.contracts) ? release.contracts[0] : undefined; const award = Array.isArray(release.awards) ? release.awards[0] : undefined; return { externalId: text(contract?.id || release.id || release.ocid || cursor + index + 1), raw: { title: release.tender?.title || contract?.id || release.id, description: release.tender?.description || award?.description || '', supplier: Array.isArray(award?.suppliers) ? award.suppliers[0]?.name : '', location: 'Australia', value: contract?.value?.amount ?? award?.value?.amount ?? '', date: release.date || '' } }; }); return { rows, next: cursor + 7, completed: cursor + 7 >= MAX_DAYS }; }

async function ckanPackage(source: BackfillSource, cursor: number): Promise<Page> { const body = await jsonFetch(source.endpoint) as any; if (body.success !== true || !Array.isArray(body.result?.resources)) throw new Error('CKAN_SCHEMA_INVALID'); const resources = [...body.result.resources].sort((a: any, b: any) => Date.parse(String(b.last_modified || b.created || 0)) - Date.parse(String(a.last_modified || a.created || 0))); const resource = resources.find((item: any) => item.datastore_active === true && item.id) || resources.find((item: any) => String(item.format || '').toUpperCase() === 'XLSX' && item.url); if (!resource) return { rows: [], next: cursor, completed: true }; if (resource.datastore_active === true && resource.id) { const page = await jsonFetch('https://www.data.qld.gov.au/api/3/action/datastore_search?resource_id=' + encodeURIComponent(resource.id) + '&limit=' + BATCH + '&offset=' + cursor) as any; const records = Array.isArray(page.result?.records) ? page.result.records : []; const rows = records.map((row: any, index: number) => ({ externalId: text(row._id || row.id || cursor + index + 1), raw: row as Record<string, unknown> })); const total = Number(page.result?.total || 0); return { rows, next: cursor + rows.length, completed: rows.length < BATCH || (total > 0 && cursor + rows.length >= total) }; } const book = await workbook(String(resource.url)); const sheet = book.SheetNames[0]; if (!sheet) return { rows: [], next: cursor, completed: true }; const all = utils.sheet_to_json<Record<string, unknown>>(book.Sheets[sheet], { defval: '' }); const rows = all.slice(cursor, cursor + BATCH).map((row, index) => ({ externalId: find(row, ['permitnumber','authoritynumber','permitreference','id']) || text(cursor + index + 1), raw: row })); return { rows, next: cursor + rows.length, completed: cursor + rows.length >= all.length }; }
async function kml(source: BackfillSource, cursor: number): Promise<Page> { const body = await jsonFetch(source.endpoint) as any; if (body.success !== true || !Array.isArray(body.result?.resources)) throw new Error('CKAN_SCHEMA_INVALID'); const resource = body.result.resources.find((item: any) => String(item.format || '').toUpperCase() === 'KML' && item.url); if (!resource?.url) throw new Error('KML_RESOURCE_MISSING'); const xml = await textFetch(String(resource.url)); const all = [...xml.matchAll(/<(?:\w+:)?Placemark\b[^>]*>([\s\S]*?)<\/(?:\w+:)?Placemark>/gi)]; const rows = all.slice(cursor, cursor + BATCH).map((match, index) => { const block = match[1]; const name = block.match(/<(?:\w+:)?name>([\s\S]*?)<\/(?:\w+:)?name>/i)?.[1]?.replace(/<[^>]+>/g, ' ').trim() || ''; const description = block.match(/<(?:\w+:)?description>([\s\S]*?)<\/(?:\w+:)?description>/i)?.[1]?.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim() || ''; return { externalId: name || text(cursor + index + 1), raw: { name, description } }; }); return { rows, next: cursor + rows.length, completed: cursor + rows.length >= all.length }; }
function geoJsonRaw(feature: any): Record<string, unknown> { const props = (feature?.properties || {}) as Record<string, unknown>; const roads = Array.isArray((props as any).roads) ? (props as any).roads : []; const road = (roads[0] || {}) as Record<string, unknown>; const title = [text(road.mainStreet) || text((props as any).name) || text((props as any).headline) || text((props as any).displayName), text((props as any).subCategoryA), text(road.suburb)].filter(Boolean).join(' · '); const location = [text(road.suburb), text(road.region)].filter(Boolean).join(', '); const description = [text((props as any).mainCategory), text((props as any).subCategoryA), stripHtml((props as any).otherAdvice)].filter(Boolean).join(' · '); return { ...props, title: title || text(feature?.id) || 'Published roadwork', road: text(road.mainStreet), suburb: text(road.suburb), region: text(road.region), location, description }; }
async function geojson(source: BackfillSource, cursor: number): Promise<Page> { const body = await jsonFetch(source.endpoint) as any; if (!Array.isArray(body.features)) throw new Error('GEOJSON_SCHEMA_INVALID'); const all = body.features; const rows = all.slice(cursor, cursor + BATCH).map((feature: any, index: number) => ({ externalId: text(feature.id || feature.properties?.id || cursor + index + 1), raw: geoJsonRaw(feature) })); return { rows, next: cursor + rows.length, completed: cursor + rows.length >= all.length }; }
async function projectXlsx(source: BackfillSource, cursor: number): Promise<Page> { const book = await workbook(source.endpoint); const all: Record<string, unknown>[] = []; for (const sheet of book.SheetNames) { const rows = utils.sheet_to_json<unknown[]>(book.Sheets[sheet], { header: 1, defval: '' }) as unknown[][]; let header = -1; for (let index = 0; index < Math.min(rows.length, 25); index++) { const cells = rows[index].map(value => text(value).toLowerCase()); if (cells.some(value => /project|generator|facility|connection/.test(value)) && cells.some(value => /name|site|region|status/.test(value))) { header = index; break; } } if (header < 0) continue; const keys = rows[header].map((value, index) => text(value) || 'column_' + index); for (const row of rows.slice(header + 1)) { const record: Record<string, unknown> = {}; keys.forEach((key, index) => { if (text(row[index])) record[key] = row[index]; }); if (Object.keys(record).length >= 2) all.push(record); if (all.length >= 20000) break; } if (all.length >= 20000) break; } const rows = all.slice(cursor, cursor + BATCH).map((row, index) => ({ externalId: find(row, ['projectname','generatorname','facilityname','connectionpoint','duid','id']) || text(cursor + index + 1), raw: row })); return { rows, next: cursor + rows.length, completed: cursor + rows.length >= all.length }; }

export async function collectBackfillPage(source: BackfillSource, cursor: number): Promise<Page> { if (source.method === 'ARCGIS') return arcgis(source, cursor); if (source.method === 'CKAN_DATASTORE') return datastore(source, cursor); if (source.method === 'CKAN_PACKAGE') return ckanPackage(source, cursor); if (source.method === 'OCDS') return ocds(source, cursor); if (source.method === 'OPENDATASOFT') return ods(source, cursor); if (source.method === 'WFS') return wfs(source, cursor); if (source.method === 'WFS_DIRECT') return wfsDirect(source, cursor); if (source.method === 'CKAN_KML') return kml(source, cursor); if (source.method === 'XLSX_PROJECT') return projectXlsx(source, cursor); if (source.method === 'GEOJSON') return geojson(source, cursor); return { rows: [], next: cursor, completed: true }; }
