import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

type DashboardLike = Record<string, any>;
export type ReportSummary = { generatedAt: string; headline: string; projectCount: number; opportunityCount: number; highPriorityCount: number; liveFeeds: string; deferredFeeds: number; evidenceProcessed: number; completedBackfill: string; predictedDemandClusters: number };

export function buildExecutiveReportSummary(dashboard: DashboardLike): ReportSummary {
  const projects = dashboard.projects || [];
  const events = dashboard.commercial?.events || [];
  const high = projects.filter((project: any) => project.priorityBand === 'HIGH').length;
  return { generatedAt: new Date().toISOString(), headline: `${projects.length} canonical projects, ${events.length} opportunity signals, ${high} high-priority projects`, projectCount: projects.length, opportunityCount: events.length, highPriorityCount: high, liveFeeds: `${dashboard.sources?.active || 0}/${dashboard.sources?.configured || 0}`, deferredFeeds: dashboard.sources?.deferred?.length || 0, evidenceProcessed: dashboard.backfill?.processed || 0, completedBackfill: `${dashboard.backfill?.completedSources || 0}/${dashboard.backfill?.totalSources || 0}`, predictedDemandClusters: dashboard.commercial?.equipmentClusters?.length || 0 };
}
function section(doc: jsPDF, title: string) { doc.addPage(); doc.setFontSize(16); doc.text(title, 14, 18); }
export function downloadExecutivePdf(dashboard: DashboardLike) {
  const summary = buildExecutiveReportSummary(dashboard); const projects = dashboard.projects || []; const events = dashboard.commercial?.events || []; const contractors = dashboard.commercial?.contractorWorkload || []; const clusters = dashboard.commercial?.equipmentClusters || []; const fleet = dashboard.commercial?.fleetPositioning || []; const calibration = dashboard.commercial?.calibration || {}; const deferred = dashboard.sources?.deferred || [];
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  doc.setFontSize(22); doc.text('Hire Intelligence', 14, 20); doc.setFontSize(15); doc.text('Executive Intelligence Report', 14, 29); doc.setFontSize(9); doc.text(`Generated ${new Date(summary.generatedAt).toLocaleString('en-AU')}`, 14, 36); doc.text('Evidence-governed equipment-rental opportunity intelligence', 14, 42);
  autoTable(doc, { startY: 50, head: [['Executive metric', 'Current position']], body: [['Canonical projects', String(summary.projectCount)], ['Opportunity signals', String(summary.opportunityCount)], ['High-priority projects', String(summary.highPriorityCount)], ['Live GREEN feeds', summary.liveFeeds], ['Deferred collectors', String(summary.deferredFeeds)], ['Historical evidence processed', summary.evidenceProcessed.toLocaleString('en-AU')], ['Backfill sources completed', summary.completedBackfill], ['PREDICTED demand clusters', String(summary.predictedDemandClusters)], ['CALL NOW', String(dashboard.metrics?.callNow || 0) + ' - separately evidence-gated']], styles: { fontSize: 8 } });
  const finalY = (doc as any).lastAutoTable?.finalY || 120; doc.setFontSize(11); doc.text('Executive interpretation', 14, finalY + 10); doc.setFontSize(9); doc.text(doc.splitTextToSize(`Hire Intelligence currently ranks ${summary.projectCount} canonical projects and ${summary.opportunityCount} evidence-derived opportunity signals. ${summary.highPriorityCount} projects are classified HIGH priority. A high priority score does not itself create CALL NOW. Equipment demand and fleet-positioning outputs are predictions from observed work evidence and are not observed hire requirements.`, 180), 14, finalY + 17);
  section(doc, 'Top Ranked Projects'); autoTable(doc, { startY: 25, head: [['Project', 'Location', 'Stage', 'Priority', 'Signal', 'PREDICTED equipment', 'Evidence']], body: projects.slice(0, 25).map((project: any) => [project.name, project.location, project.stageLabel, String(project.bdmPriority), project.signalQualityBand || '-', (project.equipmentPrediction?.classes || []).join(', ') || 'Not inferred', String(project.evidenceCount || 0)]), styles: { fontSize: 6.5, cellPadding: 1.6 } });
  section(doc, 'Current Opportunity Signals'); autoTable(doc, { startY: 25, head: [['Signal', 'Project', 'Location', 'Confidence', 'Stage', 'Recommended action']], body: events.slice(0, 35).map((event: any) => [event.type, event.project, event.location, `${event.confidence}%`, event.stage || '-', event.action || event.reason || '-']), styles: { fontSize: 6.5, cellPadding: 1.6 } });
  section(doc, 'Contractor Workload Intelligence'); autoTable(doc, { startY: 25, head: [['Contractor', 'Projects', 'High priority', 'Avg priority', 'Locations', 'PREDICTED equipment']], body: contractors.slice(0, 30).map((item: any) => [item.contractor, String(item.projectCount), String(item.highPriorityProjects), String(item.averagePriority), (item.locations || []).join(', '), (item.predictedEquipment || []).join(', ') || 'Not inferred']), styles: { fontSize: 6.5, cellPadding: 1.6 } });
  section(doc, 'PREDICTED Equipment Demand and Fleet Positioning'); autoTable(doc, { startY: 25, head: [['Location', 'Equipment class', 'Projects', 'Avg priority', 'Confidence']], body: clusters.slice(0, 30).map((item: any) => [item.location, item.equipmentClass, String(item.projectCount), String(item.averagePriority), `${item.confidence}%`]), styles: { fontSize: 7 } }); const clusterY = (doc as any).lastAutoTable?.finalY || 120; doc.setFontSize(10); doc.text('Fleet positioning watches', 14, clusterY + 10); doc.setFontSize(8); doc.text(doc.splitTextToSize(fleet.slice(0, 12).map((item: any) => `- ${item.equipmentClass} / ${item.location}: ${item.recommendation}`).join('\n') || 'No fleet-positioning watches meet the current evidence threshold.', 180), 14, clusterY + 17);
  section(doc, 'Data Health, Calibration and Governance'); autoTable(doc, { startY: 25, head: [['Data health', 'Current position']], body: [['Coverage', dashboard.coverage || '-'], ['Latest bounded source records', String(dashboard.sources?.runtimeFetched || 0)], ['Historical evidence processed', String(dashboard.backfill?.processed || 0)], ['Backfill completed', summary.completedBackfill], ['Linked genuine reviewed outcomes', String(calibration.linkedRealOutcomes || 0)], ['Unmatched legacy outcomes', String(calibration.unmatchedRealOutcomes || 0)], ['Calibration sample sufficient', calibration.sufficientSample ? 'Yes' : 'No']], styles: { fontSize: 8 } }); const dataY = (doc as any).lastAutoTable?.finalY || 105; doc.setFontSize(10); doc.text('Deferred collectors', 14, dataY + 10); autoTable(doc, { startY: dataY + 14, head: [['Source', 'Reason']], body: deferred.slice(0, 20).map((item: any) => [item.name || item.sourceKey, item.reason || 'Deferred pending revalidation']), styles: { fontSize: 6.8 } }); const govY = (doc as any).lastAutoTable?.finalY || 180; doc.setFontSize(8); doc.text(doc.splitTextToSize('Governance: contacts are not invented; BDM calls, requirements, quotes, wins and commercial values are human-entered only; equipment demand is explicitly PREDICTED; source provenance and licensing remain attached to the underlying evidence; CALL NOW remains separately evidence-gated.', 180), 14, Math.min(govY + 10, 275));
  const filename = `Hire-Intelligence-Executive-Report-${new Date().toISOString().slice(0, 10)}.pdf`; doc.save(filename); return filename;
}
